#!/bin/bash

# Obtain Puppet manifests as a git archive. (Git archives can not be
# commited to). Production hiera data is excluded.

Bin="$(cd -- "$(dirname "$0")" && pwd)"

puppet_dir=$Bin/scratch/puppet

mkdir -p $puppet_dir

git archive --remote git@git.apidb.org:puppet4.git master \
  | tar -x -C $puppet_dir \
    --exclude=code/environments/hashicorp\
    --exclude=code/environments/production/ 